### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jonom**
Hello @anilahir thank you for this module! I have done some bug fixing here, as well as refactoring a little and adding a little bit more API coverage. Please review the individual commits to better understand what has been addressed, and let me know if you have any questions.

### CODE REVIEW

**Comment by anilahir** [comment]
> Hello @anilahir thank you for this module! I have done some bug fixing here, as well as refactoring a little and adding a little bit more API coverage. Please review the individual commits to better understand what has been addressed, and let me know if you have any questions.

Thank you @jonom :+1: )

**Comment by jonom** [comment]
Thanks for the quick merge!

**Comment by jonom** [comment]
@anilahir thank you for tagging a release, it doesn't seem to have made it up to [packagist](https://packagist.org/packages/anilahir/omnipay-bambora) yet though - would you be able to set up a [github hook](https://packagist.org/about#how-to-update-packages)?

**Comment by anilahir** [comment]
@jonom already added GitHub hook but It's deprecated
It's fixed now. Please check again & let me know if anything missed

**Comment by jonom** [comment]
Looks great, thanks again!

**Pull request merged**
